/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "primary-container": "#3e52e8",
        "secondary-fixed": "#e1e2e4",
        "on-primary-fixed-variant": "#132cca",
        "on-surface": "#1a1c1f",
        "surface-bright": "#f9f9fd",
        "tertiary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dade",
        "on-secondary-fixed": "#191c1e",
        "on-secondary": "#ffffff",
        "tertiary-container": "#00734e",
        "inverse-on-surface": "#f0f0f4",
        "secondary-container": "#dee0e2",
        "on-background": "#1a1c1f",
        "secondary-fixed-dim": "#c5c6c8",
        "on-secondary-fixed-variant": "#444749",
        "surface-variant": "#e2e2e6",
        "on-tertiary-fixed": "#002113",
        "tertiary": "#00583b",
        "surface-container-highest": "#e2e2e6",
        "on-secondary-container": "#606365",
        "inverse-primary": "#bcc2ff",
        "on-error": "#ffffff",
        "on-primary-container": "#dfe0ff",
        "secondary": "#5c5f60",
        "inverse-surface": "#2f3034",
        "tertiary-fixed-dim": "#4edea3",
        "surface": "#f9f9fd",
        "background": "#f9f9fd",
        "on-tertiary-fixed-variant": "#005236",
        "surface-tint": "#364be1",
        "on-primary-fixed": "#000b62",
        "on-surface-variant": "#444655",
        "surface-container-low": "#f3f3f7",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dfe0ff",
        "primary": "#1e35d0",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e8ec",
        "on-tertiary-container": "#6efbbd",
        "primary-fixed-dim": "#bcc2ff",
        "outline": "#757687",
        "surface-container": "#eeedf2",
        "error": "#ba1a1a",
        "outline-variant": "#c5c5d8",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "grid-gap": "2px",
        "container-padding": "16px",
        "element-gap": "12px",
        "section-margin": "24px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
